Record accessor limitation
fluent/fluent-bit-docs pull request #1015
Opened 2022-12-26 18:24 UTC by RicardoAAD

Removed the Limitation section from https://docs.fluentbit.io/manual/pipeline/filters/ecs-metadata#limitations-of-record_accessor-templating and added this section to https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/record-accessor

2023-01-02 13:46 UTC, lecaros requested changes

2023-01-02 13:46 UTC, lecaros commented on administration/configuring-fluent-bit/classic-mode/record-accessor.md
> +Notice in the example from [Record accessor template usage](../../../pipeline/filters/ecs-metadata.md#example-2-attach-customized-resource-name-to-container-logs), that the template values are separa
The reference should be from the example to this page, not the opposite.

2023-01-04 03:24 UTC, RicardoAAD commented
Changes were made

2023-10-09 13:10 UTC, lecaros approved these changes

2023-10-09 13:10 UTC, merged