development: add development environment docs
fluent/fluent-bit-docs pull request #1055
Opened 2023-02-28 21:39 UTC by bkayranci

Fluent-bit will provide isolated environment for development. Devcontainer is added as an alternative to Vagrant. The document about creating development environment is added and refered development guide repos.

- [Devcontainer Support PR](https://github.com/fluent/fluent-bit/pull/6880)

2023-03-01 10:47 UTC, patrick-stephens requested changes

2023-03-01 10:47 UTC, patrick-stephens commented on development/developer-guide.md
> +Fluent-bit provides an isolated environment from local environment for development. Thanks to that, developer who use different OSes / distros do not have to try finding available required libraries
Please use separate lines for each sentence - it makes commenting easier.

```suggestion
Fluent-bit provides a standalone environment for development. 
Developers who use different OS or distributions can develop on a simple, common stack. 
The development environment provides the required libraries and tools for you.
```

2023-03-01 10:47 UTC, patrick-stephens commented on development/developer-guide.md
> +Development environments by fluent-bit provided are able to create via [Devcontainer](https://github.com/fluent/fluent-bit/blob/master/DEVELOPER_GUIDE.md#devcontainer) or [Vagrant](https://github.com
Inconsistent `fluent-bit` vs `Fluent-bit`

2023-03-01 10:47 UTC, patrick-stephens commented on development/developer-guide.md
> +Development environments by fluent-bit provided are able to create via [Devcontainer](https://github.com/fluent/fluent-bit/blob/master/DEVELOPER_GUIDE.md#devcontainer) or [Vagrant](https://github.com
```suggestion
Development environments provided for
- [Devcontainer](https://github.com/fluent/fluent-bit/blob/master/DEVELOPER_GUIDE.md#devcontainer)
- [Vagrant](https://github.com/fluent/fluent-bit/blob/master/DEVELOPER_GUIDE.md#vagrant).
```

2023-03-01 21:37 UTC, bkayranci commented
@patrick-stephens thank you for your review :rocket:

2023-03-02 11:19 UTC, patrick-stephens approved these changes

2023-03-02 11:20 UTC, patrick-stephens commented
@bkayranci I cannot merge as some of the commits are not signed...

2023-03-02 18:07 UTC, bkayranci commented
> @bkayranci I cannot merge as some of the commits are not signed...

Which commits were not signed? [The DCO test](https://github.com/fluent/fluent-bit-docs/pull/1055/checks) is passing. There are "Signed-off-by" on  all commits.

2023-03-02 19:02 UTC, bkayranci commented
@patrick-stephens I found and fixed the not signed commit :+1: 

Could you try to merge again please? :rocket:

2023-03-03 09:08 UTC, merged