filter: delete redundant standard output page
fluent/fluent-bit-docs pull request #528
Opened 2021-05-06 10:10 UTC by Huweicai

Fix a error as mentioned in #358, **Standard Output** is already in Outputs chapter, so it needs to be deleted.

2021-05-06 11:23 UTC, nokute78 commented
Thank you for contribution.

Fluent-bit supports `filter_stdout` plugin. [source code](https://github.com/fluent/fluent-bit/tree/master/plugins/filter_stdout) 
So, it is better to rewrite description.
Can you rewrite it ?

The plugin has no cofiguration parameters, just outputs log.
We can test the following command and options.
```
$/fluent-bit -i cpu -F stdout -m '*' -o null
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/05/06 20:22:32] [ info] [engine] started (pid=5679)
[2021/05/06 20:22:32] [ info] [storage] version=1.1.1, initializing...
[2021/05/06 20:22:32] [ info] [storage] in-memory
[2021/05/06 20:22:32] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/05/06 20:22:32] [ info] [sp] stream processor started
[0] cpu.0: [1620300152.505191493, {"cpu_p"=>2.000000, "user_p"=>2.000000, "system_p"=>0.000000, "cpu0.p_cpu"=>2.000000, "cpu0.p_user"=>2.000000, "cpu0.p_system"=>0.000000}]
[0] cpu.0: [1620300153.505461050, {"cpu_p"=>2.000000, "user_p"=>2.000000, "system_p"=>0.000000, "cpu0.p_cpu"=>2.000000, "cpu0.p_user"=>2.000000, "cpu0.p_system"=>0.000000}]
^C[2021/05/06 20:22:34] [engine] caught signal (SIGINT)
[2021/05/06 20:22:34] [ info] [input] pausing cpu.0
[2021/05/06 20:22:34] [ warn] [engine] service will stop in 5 seconds
[2021/05/06 20:22:38] [ info] [engine] service stopped
$ 
```

2021-05-08 08:35 UTC, Huweicai commented
> Thank you for contribution.
> 
> Fluent-bit supports `filter_stdout` plugin. [source code](https://github.com/fluent/fluent-bit/tree/master/plugins/filter_stdout)
> So, it is better to rewrite description.
> Can you rewrite it ?
> 
> The plugin has no cofiguration parameters, just outputs log.
> We can test the following command and options.
> 
> ```
> $/fluent-bit -i cpu -F stdout -m '*' -o null
> Fluent Bit v1.8.0
> * Copyright (C) 2019-2021 The Fluent Bit Authors
> * Copyright (C) 2015-2018 Treasure Data
> * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
> * https://fluentbit.io
> 
> [2021/05/06 20:22:32] [ info] [engine] started (pid=5679)
> [2021/05/06 20:22:32] [ info] [storage] version=1.1.1, initializing...
> [2021/05/06 20:22:32] [ info] [storage] in-memory
> [2021/05/06 20:22:32] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
> [2021/05/06 20:22:32] [ info] [sp] stream processor started
> [0] cpu.0: [1620300152.505191493, {"cpu_p"=>2.000000, "user_p"=>2.000000, "system_p"=>0.000000, "cpu0.p_cpu"=>2.000000, "cpu0.p_user"=>2.000000, "cpu0.p_system"=>0.000000}]
> [0] cpu.0: [1620300153.505461050, {"cpu_p"=>2.000000, "user_p"=>2.000000, "system_p"=>0.000000, "cpu0.p_cpu"=>2.000000, "cpu0.p_user"=>2.000000, "cpu0.p_system"=>0.000000}]
> ^C[2021/05/06 20:22:34] [engine] caught signal (SIGINT)
> [2021/05/06 20:22:34] [ info] [input] pausing cpu.0
> [2021/05/06 20:22:34] [ warn] [engine] service will stop in 5 seconds
> [2021/05/06 20:22:38] [ info] [engine] service stopped
> $ 
> ```

OK，I'll have a try on it.

2021-06-04 07:49 UTC, Huweicai commented
@nokute78 I rewrited it, please have a look again.

2021-06-04 22:06 UTC, nokute78 requested changes
Thank you for updating.

I reviewed and can you check them ?

2021-06-04 22:06 UTC, nokute78 commented on pipeline/filters/standard-output.md
> +$ bin/fluent-bit -i cpu -F stdout -m '*' -o null
It is better to use `fluent-bit`.
`bin/fluent-bit` is not proper path in some environments.

2021-06-04 22:06 UTC, nokute78 commented on pipeline/filters/standard-output.md
> +We have specified to gather [CPU](https://github.com/fluent/fluent-bit-docs/tree/ddc1cf3d996966b9db39f8784596c8b7132b4d5b/pipeline/input/cpu.md) usage metrics and print them out in a human-readable w
The link CPU is broken.
The path is `../inputs/cpu-metrics.md`

2021-06-04 22:06 UTC, nokute78 commented on pipeline/filters/standard-output.md
> +We have specified to gather [CPU](https://github.com/fluent/fluent-bit-docs/tree/ddc1cf3d996966b9db39f8784596c8b7132b4d5b/pipeline/input/cpu.md) usage metrics and print them out in a human-readable w
I think the description about `-m` is not needed.
Because `-m` is not unique option for filter_stdout plugin.

2021-06-04 22:06 UTC, nokute78 commented on pipeline/filters/standard-output.md
> -# Standard Output
Can you add `# Standard Output`  again?
I think it will be same format like other plugins.

2021-06-07 03:12 UTC, Huweicai commented
Modified as you reviewed, please hava a look again~ @nokute78

2021-06-07 11:48 UTC, nokute78 commented
@Huweicai Thank you for updating. Looks good to me!

2021-06-07 11:49 UTC, nokute78 approved these changes

2021-06-21 06:12 UTC, Huweicai commented
@agup006 Would you please merge it ~

2021-09-04 22:51 UTC, nokute78 commented
@edsiper @agup006 Could you merge this ?
The issue is also reported on fluent-bit repo.
https://github.com/fluent/fluent-bit/issues/4057

2021-09-05 00:48 UTC, merged

2021-09-06 03:46 UTC, Huweicai commented
@nokute78 https://github.com/fluent/fluent-bit-docs/pull/578 this pr can be closed, too.