monitoring: add detailed descriptions for each metric
fluent/fluent-bit-docs pull request #856
Opened 2022-08-02 00:09 UTC by PettitWesley

Signed-off-by: Wesley Pettit <wppttt@amazon.com>

2022-08-02 00:42 UTC, edsiper commented
cc: @lecaros

2022-08-03 00:03 UTC, DrewZhang13 reviewed
There are several blank rows and columns in the second table, is it expected?

2022-08-03 20:09 UTC, PettitWesley commented
@DrewZhang13 that seems to be something weird the markdown table generation thing I used added... thanks, I will fix it

2022-08-17 10:51 UTC, patrick-stephens commented
This would be good to merge, are we ok now @PettitWesley @DrewZhang13 @lecaros ?

2022-08-17 19:47 UTC, PettitWesley commented
@patrick-stephens @lecaros I want someone outside of my own team (So not Drew) to validate that this is all correct (with an approval) before we merge it.

2022-08-17 20:14 UTC, lecaros requested changes

2022-08-17 20:16 UTC, lecaros commented
Hi everyone, sorry I didn't send the review. I just left it there pending. Besides those 2 changes (fluentbit_output_proc_records_total and fluentbit_output_proc_bytes_total), the docs are great!

2022-08-17 20:51 UTC, PettitWesley commented on administration/monitoring.md
> +| fluentbit_output_retries_failed_total  | name: the name or alias for the input instance  | The number of times that retries expired for a chunk. Each plugin configures a Retry_Limit which applies t
Oops I keep saying input for all of these even for the output metrics...

2022-08-17 21:09 UTC, PettitWesley commented
@lecaros thanks. I updated it. If you can approve now then we can merge.

2022-08-18 15:28 UTC, merged

2022-08-18 15:29 UTC, lecaros commented
Thanks for your contribution @PettitWesley! I've merged it.