Network add
fluent/fluent-bit-docs pull request #889
Opened 2022-09-05 21:07 UTC by LatorreDev

2022-09-09 00:19 UTC, edsiper requested changes

2022-09-09 00:19 UTC, edsiper commented on administration/networking.md
> +| `custom_k8s_regex` | Set a custom kubernetes regex filter | (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker
this seems to be wrong

2022-09-09 00:19 UTC, edsiper commented on administration/networking.md
> +| `resource_labels` | Set the resource labels |  |
wrong location

2022-09-12 22:01 UTC, merged

2022-09-12 22:02 UTC, lecaros commented
Thanks @LatorreDev for your contribution! I've merged it.